/**
 * Common fields for all endpoints
 *
 * TODO: add params
 */
export const getCommonFields = () => {
  return {
    openapi: '3.1.0',
    info: {
      title: 'Typo shield swagger',
      description: 'Auto generated by typo-shield-swagger-generator package',
      version: '1.0.0',
    },
    servers: [
      {
        url: 'http://localhost:3000',
        description: 'Localhost',
      },
    ],
  };
};
